group 'appmire.be.flutterjailbreakdetection'
version '1.0-SNAPSHOT'

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace 'appmire.be.flutterjailbreakdetection'

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdkVersion 17
        compileSdk 36
    }
}

dependencies {
    implementation 'com.scottyab:rootbeer-lib:0.1.1'
}
